# https://code.visualstudio.com/api/working-with-extensions/continuous-integration

name: ReleaseAssets

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      env:
        CXX: "g++-4.9"
        CC: "gcc-4.9"
        DISPLAY: ":99.0"
      run: yarn install

    - name: create package
      env:
        HUSKY_SKIP_INSTALL: "true"
        CXX: "g++-4.9"
        CC: "gcc-4.9"
        DISPLAY: ":99.0"
      run: yarn run package

    - name: Upload to Release
      uses: OmgImAlexis/upload-to-release@12da88e9f14252a5232be13ee9aadda64637c271
      with:
        args: "*.vsix"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
